# Generated by Django 2.2.10 on 2020-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0005_auto_20200809_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
    ]
