# Generated by Django 2.2.10 on 2020-08-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0007_eventaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventaction',
            old_name='desc',
            new_name='raw_html',
        ),
    ]
