# Generated by Django 2.2.10 on 2020-08-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0012_auto_20200821_0818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostnameMunicipality',
            new_name='MunicipalityHostname',
        ),
    ]
