# Generated by Django 2.2.10 on 2020-08-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0014_auto_20200823_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='confirmed_date',
        ),
    ]
