# Generated by Django 2.2.10 on 2020-08-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0016_auto_20200823_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventaction',
            name='confirmed_date',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
