# Generated by Django 2.2.10 on 2020-08-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0017_eventaction_confirmed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalityhostname',
            name='muni',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='idp_data.Municipality'),
        ),
    ]
