# Generated by Django 2.2.10 on 2020-08-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0018_auto_20200824_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='muni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idp_data.Municipality'),
        ),
        migrations.AlterField(
            model_name='municipalityhostname',
            name='muni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idp_data.Municipality'),
        ),
    ]
