# Generated by Django 2.2.10 on 2020-09-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0019_auto_20200827_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalityhostname',
            name='homepageURL',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
