# Generated by Django 2.2.10 on 2020-09-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0021_auto_20200903_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='homepageURL',
        ),
    ]
