# Generated by Django 2.2.10 on 2020-09-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0022_remove_municipality_homepageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='homepage_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
