# Generated by Django 2.2.10 on 2020-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0025_municipality_ward_councillor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='by_laws_url',
            field=models.CharField(max_length=500, verbose_name='By Laws URL'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='homepage_url',
            field=models.CharField(max_length=500, verbose_name='Homepage URL'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='ward_councillor_url',
            field=models.CharField(max_length=500, verbose_name='Find Your Ward Councillor URL'),
        ),
    ]
