# Generated by Django 2.2.10 on 2020-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0027_municipality_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='page_title',
            field=models.CharField(default='Public Participation Guide', max_length=200, verbose_name='Page Title'),
        ),
    ]
