# Generated by Django 2.2.10 on 2021-02-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0028_auto_20201201_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='colour_primary_fill',
            field=models.CharField(default='ff8c00', help_text='CSS hex colour code e.g. ff8c00', max_length=6, verbose_name='Custom primary fill colour'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='colour_primary_text',
            field=models.CharField(default='ff8c00', help_text='CSS hex colour code e.g. ff8c00', max_length=6, verbose_name='Custom primary text colour'),
        ),
    ]
