# Generated by Django 2.2.10 on 2021-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0029_auto_20210218_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', help_text='This is shown to users.', max_length=1000),
        ),
    ]
