# Generated by Django 2.2.10 on 2021-03-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0031_auto_20210304_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='financial_performance_url',
            field=models.CharField(default='', max_length=500, verbose_name='Financial Performance URL'),
        ),
    ]
