# Generated by Django 2.2.10 on 2021-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0033_category_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='comment_open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
