# Generated by Django 2.2.10 on 2021-03-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0035_eventsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubmission',
            name='submitted',
            field=models.DateTimeField(),
        ),
    ]
