# Generated by Django 2.2.10 on 2021-03-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0037_auto_20210331_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='submission_issue',
            field=models.CharField(default='Municipal', max_length=500),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='submitter_town',
            field=models.CharField(default='Bitterfontein', max_length=500),
        ),
    ]
