# Generated by Django 2.2.10 on 2021-04-01 13:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0038_auto_20210331_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='towns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='eventsubmission',
            name='submission',
            field=models.TextField(max_length=5000),
        ),
    ]
