# Generated by Django 2.2.10 on 2021-04-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0039_auto_20210401_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='recaptcha_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
