# Generated by Django 2.2.10 on 2021-04-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0040_eventsubmission_recaptcha_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='event_submission_email_address',
            field=models.EmailField(help_text='The email address any event submissions (comments) should be sent to.', max_length=254, null=True),
        ),
    ]
