# Generated by Django 2.2.10 on 2021-04-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0042_auto_20210415_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='event_submission_form_enabled',
            field=models.BooleanField(default=False, help_text='Whether this municipality will show the comment form for active engagements.'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='enquiry_email_address',
            field=models.EmailField(blank=True, help_text='The email address shown after event submissions.', max_length=254, null=True),
        ),
    ]
