# Generated by Django 2.2.10 on 2021-04-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0044_event_modal_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventaction',
            name='extra',
            field=models.BooleanField(default=False, help_text='Extra actions are only shown in the modal'),
        ),
    ]
