# Generated by Django 2.2.10 on 2021-04-30 12:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0045_eventaction_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(default='', help_text='The heading this info will be grouped under', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(default='', help_text='This is shown to users.', max_length=1000),
        ),
    ]
