# Generated by Django 2.2.10 on 2021-04-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0046_auto_20210430_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='public',
        ),
    ]
