# Generated by Django 2.2.10 on 2021-05-03 14:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idp_data', '0047_remove_category_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='post_submission_message',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Shown after an even submission has been made.', null=True),
        ),
    ]
