name: Python package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          docker-compose run --rm web yarn
      - name: Test
        run: |
          docker-compose run --rm web yarn build
          docker-compose run --rm web python manage.py collectstatic --no-input
          docker-compose run --rm web bin/wait-for-postgres.sh coverage run --source=idp_data manage.py test
      - name: After test
        run: |
          docker-compose logs db
          docker-compose run --rm `bash <(curl -s https://codecov.io/env)` web codecov
